// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ipwyjfinoulgpfyijaun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlwd3lqZmlub3VsZ3BmeWlqYXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5MzYyNzAsImV4cCI6MjA5NjUxMjI3MH0.-mej4mGnXssfCMkcWEOHGyE0E4qYGg7WyfOJZj8pXLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);